# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-15 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10, verbose_name='Roll NO')),
                ('full_name', models.CharField(max_length=40, verbose_name='FULL NAME')),
                ('assignment', models.FileField(upload_to='')),
                ('time_stamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, verbose_name='subject')),
                ('Course', models.CharField(max_length=20, verbose_name='Course-sem')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects_Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40, verbose_name='subject')),
                ('assignment_given', models.FileField(upload_to='', verbose_name='Assignment')),
                ('solution', models.FileField(upload_to='', verbose_name='Solution')),
                ('date_of_submission', models.DateField(verbose_name='Last Date of Submission')),
                ('course', models.CharField(choices=[('PMCS-1', 'PMCS-1'), ('PMCS-2', 'PMCS-2'), ('PMCS-3', 'PMCS-3'), ('PMCS-4', 'PMCS-4'), ('PMCS-5', 'PMCS-5'), ('PMCS-6', 'PMCS-6'), ('CS-1', 'CS-1'), ('CS-2', 'CS-2'), ('CS-3', 'CS-3'), ('CS-4', 'CS-4'), ('CS-5', 'CS-5'), ('CS-6', 'CS-6')], max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Subjects_Teaching'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
